-- Project River — Stage 5 P3 — Limited Supabase role (RA.3)
--
-- Creates `river_agent_read`, a role that mimics the current set of operations
-- performed by River agents *except* writes that should only flow through the
-- service-role path (deploy, dedup, schema ops) or through the dashboard path
-- (CA approval gate from Stage 4).
--
-- Apply path:
--   1. Populate the 1Password vault (`bash scripts/op-setup.sh`). The setup
--      script generates a fresh password for "River Agent Read".
--   2. Read the password: `op read 'op://River/River Agent Read/password'`
--   3. Substitute it into the LOGIN PASSWORD line below (or run with
--      `psql -v agent_read_password="<value>" -f scripts/supabase-limited-role.sql`).
--   4. Apply to CBS Supabase (eptugqwlgsmwhnubbqsk) via SQL Editor.
--   5. Repeat for WR Supabase (imbskgjkqvadnazzhbiw) — the DDL is schema-compatible
--      with both projects.
--
-- Idempotency: DROP POLICY statements are wrapped in DO blocks; the CREATE ROLE
-- guard also tolerates re-runs.

BEGIN;

-- ---------- 1. Role ----------

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'river_agent_read') THEN
        -- Substitute the password generated by scripts/op-setup.sh before applying,
        -- or run this file with: psql -v agent_read_password="<value>" ...
        -- DO NOT commit an actual password to this file.
        EXECUTE format(
            'CREATE ROLE river_agent_read LOGIN PASSWORD %L',
            current_setting('myapp.agent_read_password', true)
        );
    END IF;
END
$$;

-- CREATE ROLE above defaults to NOSUPERUSER and NOBYPASSRLS, which is what
-- we want. A belt-and-braces `ALTER ROLE ... NOSUPERUSER NOBYPASSRLS` is NOT
-- used here because Supabase cloud does not grant the calling `postgres` role
-- permission to run ALTER ROLE against other roles (the cloud `postgres` is
-- not a true superuser). The CREATE ROLE defaults give us the desired scope.

-- ---------- 2. Read-path grants ----------
--
-- The CBS and WR Supabase projects are intentionally schema-divergent
-- (see docs/architecture-decisions/ADR-002-schema-divergence.md). CBS
-- has the full evaluator schema (agent_traces, evaluation_scores,
-- rubric_versions, correction_proposals); WR has only the knowledge
-- base + governance + tender tables. The grant blocks below are wrapped
-- in table-existence checks so the same file can be applied to either
-- project without error.

GRANT USAGE ON SCHEMA public TO river_agent_read;

DO $$
BEGIN
    -- Always present (KB)
    IF to_regclass('public.documents') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT ON public.documents TO river_agent_read';
    END IF;
    IF to_regclass('public.prompt_templates') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT ON public.prompt_templates TO river_agent_read';
    END IF;
    IF to_regclass('public.governance_register') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT ON public.governance_register TO river_agent_read';
    END IF;
    -- CBS-only (evaluator schema)
    IF to_regclass('public.rubric_versions') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT ON public.rubric_versions TO river_agent_read';
    END IF;
    IF to_regclass('public.agent_traces') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT, INSERT ON public.agent_traces TO river_agent_read';
    END IF;
    IF to_regclass('public.evaluation_scores') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT ON public.evaluation_scores TO river_agent_read';
    END IF;
    IF to_regclass('public.correction_proposals') IS NOT NULL THEN
        EXECUTE 'GRANT SELECT ON public.correction_proposals TO river_agent_read';
    END IF;
END
$$;

-- Sequence access for any tables that use SERIAL / BIGSERIAL and are
-- insertable by the role.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO river_agent_read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO river_agent_read;

-- ---------- 3. tender_register — column-level grant ----------
-- Agents update lifecycle metadata but MUST NOT set ca_send_approved.
-- The approval flag is only flippable via the service-role/dashboard path,
-- preserving the Stage 4 CA approval gate at the role level.

DO $$
BEGIN
    IF to_regclass('public.tender_register') IS NOT NULL THEN
        EXECUTE 'REVOKE ALL ON public.tender_register FROM river_agent_read';
        EXECUTE 'GRANT SELECT ON public.tender_register TO river_agent_read';
        EXECUTE $grant$
            GRANT UPDATE (
                lifecycle_stage,
                interest_score,
                interest_reasons,
                interest_assessed_at,
                tender_contact_name,
                tender_contact_email,
                ca_template_drive_id,
                ca_filled_drive_id,
                ca_drafted_at,
                ca_sent_at,
                ca_sent_via,
                ca_sent_message_id,
                docs_received_at,
                drive_folder_id,
                drive_folder_url,
                doc_count,
                go_no_go_scorecard,
                go_no_go_recommendation,
                go_no_go_assessed_at
            ) ON public.tender_register TO river_agent_read
        $grant$;
    END IF;
END
$$;

-- Explicitly: ca_send_approved, ca_send_approved_by, ca_send_approved_at,
-- decision, decision_date, decision_by, decision_notes are NOT granted.

-- ---------- 4. RLS on documents ----------

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'documents'
          AND policyname = 'agent_read_documents'
    ) THEN
        DROP POLICY agent_read_documents ON public.documents;
    END IF;
END
$$;

-- Permissive read policy — entity filtering is application-level. The RLS
-- toggle forces any future policy change to go through SQL review rather
-- than an unmonitored backdoor. Service-role continues to bypass RLS.
CREATE POLICY agent_read_documents ON public.documents
    FOR SELECT
    TO river_agent_read
    USING (true);

-- ---------- 5. Deny-listed operations ----------
-- Explicit REVOKEs so the intent is discoverable. Postgres defaults already
-- block these, but we want the statements to survive schema migrations.

DO $$
BEGIN
    EXECUTE 'REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.documents FROM river_agent_read';
    IF to_regclass('public.agent_traces') IS NOT NULL THEN
        EXECUTE 'REVOKE UPDATE, DELETE ON public.agent_traces FROM river_agent_read';
    END IF;
    IF to_regclass('public.rubric_versions') IS NOT NULL THEN
        EXECUTE 'REVOKE ALL ON public.rubric_versions FROM river_agent_read';
        EXECUTE 'GRANT SELECT ON public.rubric_versions TO river_agent_read';
    END IF;
    IF to_regclass('public.correction_proposals') IS NOT NULL THEN
        EXECUTE 'REVOKE ALL ON public.correction_proposals FROM river_agent_read';
        EXECUTE 'GRANT SELECT ON public.correction_proposals TO river_agent_read';
    END IF;
END
$$;

COMMIT;

-- ---------- Verification ----------

-- Run these after applying to confirm the role is correctly scoped:
--   SELECT rolname, rolsuper, rolbypassrls FROM pg_roles WHERE rolname='river_agent_read';
--   SELECT * FROM information_schema.role_table_grants WHERE grantee='river_agent_read';
--   SELECT policyname, cmd, roles FROM pg_policies WHERE tablename='documents';
